import PDFDocument from 'pdfkit';
import { IFormularyComparisonSummary } from './formularyComparison.service';

export const generateFormularyPDF = async (
  summary: IFormularyComparisonSummary,
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers: Buffer[] = [];

    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // --- Header ---
    doc
      .fillColor('#2c3e50')
      .fontSize(20)
      .text('4sightRX Formulary Reconciliation Report', { align: 'center' });
    doc.moveDown();

    // --- Patient Information ---
    const patient = summary.changedMedications[0]?.patientId || 
                    summary.continuedMedications[0]?.patientId || 
                    summary.discontinuedMedications[0]?.patientId;

    if (patient && typeof patient === 'object') {
      doc
        .fontSize(12)
        .fillColor('#34495e')
        .text('Patient Information', { underline: true });
      doc.moveDown(0.5);

      const p: any = patient;
      const patientData = [
        `Name: ${p.firstName} ${p.lastName}`,
        `MRN: ${p.patientIdMrn || 'N/A'}`,
        `Date of Birth: ${p.dateOfBirth || 'N/A'}`,
        `Admission Date: ${p.admissionDate || 'N/A'}`,
      ];

      patientData.forEach(line => doc.fontSize(10).text(line));
      doc.moveDown();
    }

    // --- Summary Section ---
    doc
      .fontSize(14)
      .fillColor('#27ae60')
      .text(`Total Estimated Monthly Savings: $${summary.totalEstimatedMonthlySavings}`, {
        align: 'right',
      });
    doc.moveDown();

    // --- Sections ---
    const renderSection = (title: string, data: any[], color: string) => {
      if (data.length === 0) return;

      doc.fontSize(14).fillColor(color).text(title, { underline: true });
      doc.moveDown(0.5);

      data.forEach((item, index) => {
        doc
          .fontSize(11)
          .fillColor('#2c3e50')
          .text(`${index + 1}. Current: ${item.currentMedication}`, { continued: true })
          .fillColor('#7f8c8d')
          .text(`  ->  Recommended: ${item.recommendedMedication}`);
        
        doc
          .fontSize(9)
          .fillColor('#34495e')
          .text(`Rationale: ${item.rationale || 'N/A'}`);
        
        if (item.estimatedSavings > 0) {
          doc.text(`Savings: $${item.estimatedSavings}`);
        }
        
        doc.moveDown(0.5);
        
        // Draw a light line between items
        if (index < data.length - 1) {
          doc
            .moveTo(doc.x, doc.y)
            .lineTo(550, doc.y)
            .strokeColor('#ecf0f1')
            .stroke();
          doc.moveDown(0.5);
        }
      });
      doc.moveDown();
    };

    renderSection('Changed Medications (Accepted)', summary.changedMedications, '#2980b9');
    renderSection('Continued Medications', summary.continuedMedications, '#f39c12');
    renderSection('Discontinued Medications', summary.discontinuedMedications, '#c0392b');

    // --- Footer ---
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(8)
        .fillColor('#95a5a6')
        .text(
          `Generated by 4sightRX | Date: ${new Date().toLocaleDateString()} | Page ${i + 1} of ${pages.count}`,
          50,
          doc.page.height - 50,
          { align: 'center' },
        );
    }

    doc.end();
  });
};
